# Generated by Django 5.1.5 on 2025-01-30 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Book must have at least one page.'), django.core.validators.MaxValueValidator(10000, message='Book must have at most 10,000 page.')]),
        ),
    ]
