# Generated by Django 5.1.5 on 2025-01-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0002_alter_book_page_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_isbn_54becd_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn', 'title'], name='books_book_isbn_bc59c4_idx'),
        ),
    ]
