# Generated by Django 5.1.5 on 2025-01-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Reader', 'reader')], default='Reader', max_length=10),
        ),
    ]
