# Generated by Django 5.1.5 on 2025-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_role'),
        ('books', '0002_alter_book_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorite_books', to='books.book'),
        ),
    ]
